### ISSUE TITLE
Electron support. Error: A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by zhex900** [cmake-js/cmake-js#244] opened 2021-06-17 04:03 UTC
Hi,

I am trying to rebuild `aws-crt` for electron on windows. 

https://github.com/zhex900/aws-crt-nodejs

I have added this to `package.json`

```
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "13.1.0",
    "arch": "x64"
  }
```

`cmake-js compile cmake`

Did successfully build with no errors. 

After I copied the `aws-crt` node module to my electron node_modules

I still get this error:

````
App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Code\mir-kiosk-electron\electron-kiosk\node_modules\aws-crt\dist\bin\win32-x64\aws-crt-nodejs.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1846)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1138:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1846)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12684)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (C:\Code\mir-kiosk-electron\electron-kiosk\.webpack\main\index.js:8461:19)
    at Object../node_modules/aws-crt/dist/native/binding.js (C:\Code\mir-kiosk-electron\electron-kiosk\.webpack\main\index.js:8470:30)
````

Do you have any idea why?

**Comment by Julusian** [comment] 2022-05-09 16:22
I expect this is a duplicate of #267, continuing discussion there

**Closed by Julusian** 2022-05-09 16:22 UTC

**Comment by arthuritoker** [comment] 2022-05-23 03:44
@zhex900 Have you resolved this issue? I have this on Mac as well.

**Comment by zhex900** [comment] 2022-05-23 03:46
No, I gave up. I stop using `aws-crt`

**Comment by arthuritoker** [comment] 2022-05-23 03:47
I got you. Thanks for the quick answer!
