### ISSUE TITLE
Native node module not building on (post)install hook

### ISSUE THREAD

**Issue by ivancuric** [cmake-js/cmake-js#229] opened 2021-01-14 16:45 UTC
I have a native module in the project directory, referenced in `/package.json` as ` "video-module": "file:video-module"`.

The `/video-module/package.json` has a the following script:
```json
  "scripts": {
    "install": "cmake-js compile",
  },
```

If I manually go to `/video-module/` and run `yarn install` the module is built.

However, running `yarn install` from the root fails the build:
```sh
[4/4] Rebuilding all packages...
[1/5] ⠂ video-module
[2/5] ⠂ core-js
[3/5] ⠂ lzma-native
[4/5] ⠂ core-js-pure
error D:\dev\my-project\node_modules\video-module: Command failed.
Exit code: 1
Command: cmake-js compile
Arguments:
Directory: D:\dev\my-project\node_modules\video-module
```

The `video-module` is moved into `/node_modules`, but there is no `build` or `node_modules` folder there.
Manually running `yarn install` from `/node-modules/video-module` builds it.

This is the `package.json` of the module:
```json
{
  "cmake-js": {
    "runtime": "electron",
    "runtimeVersion": "11.0.3"
  },
  "dependencies": {
    "node-addon-api": "^3.1.0"
  },
  "devDependencies": {
    "cmake-js": "^6.1.0"
  },
  "main": "video-module.ts",
  "name": "video-module",
  "scripts": {
    "install": "cmake-js compile",
    "make": "cmake-js compile"
  },
  "version": "1.0.0"
}
```

**Comment by Julusian** [comment] 2022-05-12 17:09
Duplicate of #230

**Closed by Julusian** 2022-05-12 17:09 UTC
